language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "khazelrigg-github"
    token:
      secure: "ltjtHBU8ls9ZrIIlfuufCtrHLEQryHcuu8VInJNrvhu4h68Nt+I04nfDN7moKaW+bweSg4u7TNHvZfYf6A+wRwIkY8LP35Wymu/cOSD6nBiablRE96IoxL//gDxxbp0wjDBKLM9Hy9HxonXNwL2TYjLQpL5DZ9LgeVTF6+fOl+UMnDs6NANeHdahjQ+FM9WT9TzcvUSxOwEBcyPpmjh8/CKQbBGhrZFq0ukaRLiiH1ppJJBqPOPAeB+6msgfg8jJ6MVHek6RX9sC3MGtxxGPcbne/49NBcICXAvqca4UlYlQhA/wlrnHPwPj9//q5JX51uj8nq99p1Hbp+QGcvr0FWlKGD7ionSkCbnL7Zzryfvx6fHKPYe1Jnmo1ApFo/PYbu4A068Oe6XoFr87xA7rDPl6DI41wJjJEMv8qajnfUMo9cEUezR1xEaccj3hQoGgWb7hDwbkVR9P0cxUJho12undStWJ+2y8llwIg7lF0KBmcK0M2Dpg03Qcjr3cNYEDsknKGYt3/ahCOJUC1Im/GdKzBKQM2P366bpLYv1s3SLfEJIqnV6+hhO46xepZ91WeY2mARbRmytFLC8GHR+DwqEAFNKGQ46yyRP7CHUZMi/xq+CKViE2TzcB4WrN8l/u6lVBc03TeRzDPhhOwnq+mdJ+k3VUehEgses+tpT6g6A="

jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
tra