language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "khazelrigg-github"
    token:
      secure: "HDPNO3l5AYCtNEyRuADTRBjzmbvpD6Co/KF2CRg92lOK4kQD0YXTkrYuoPZk6txY8cR6DFIQde7nCSS1JXERKaID15RNLeckIBBgkSl0TqmHfIpSu/nrcPrS7PcA5L3VSDqel6VQPWjSgZv3Mcz6orGIuPiTG3M8pCx8lu5mBH/eg1LIaO0e16IzzljrobNHXTp6y90laWQAhfVzBbNMN36uoE10rZivE0msodrbu/KI/qNPq7ApfQCg/XjVW5bOVOcBzREflK1yAAnXCHQu+6yjOQ2W7CmNvLbOjh1O0gjK81a+5ITUkGlYcct0tqKGvTAqFdmKnKn9yvjuJ876S/MxVi8cixzeJpAGEDXzOpajX4xwe7UTznjJKyBOfSc42rc/NErUtmBkjuTkhEEu6Ieqsrvpdv+hXDaNxMobwGn5HvHwNvxOAx41WLb1l1dCfBjldaLtdsNgampniddXfEf7At1+FvXX3bza9zT+giAptAcaUDE26WGyDQyMfmQFZ9kaKMMEGmBH+6dOnL9+G4MKzs2kKg19vZnKkcM+HIJW1B2OB6NWUGLYJfi/+mzqgkA6Njavf3duMMX6yjHC3r7hxdpNqFdX6e0MI6zOe3/goqs7oYyqHQ/gWgWJZ8sfe5YoF//kH6a+kGpcQ/QQOqjqFNqgNFICiPF7+qHRGBo="
 jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'